// Generated by CoffeeScript 1.9.3
(function() {
  var JadePhpCompiler, jade, jade2php;

  JadePhpCompiler = require('./JadePhpCompiler');

  jade = require('jade');

  module.exports = jade2php = function(str, options) {
    var compiler, parser, tokens;
    if (options == null) {
      options = {
        filename: ''
      };
    }
    parser = new jade.Parser(str, options.filename, options);
    tokens = parser.parse();
    compiler = new JadePhpCompiler(tokens, options);
    return compiler.compile();
  };

}).call(this);
